baseURL: "https://ali-hindy.github.io/"
title: Ali Hindy
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5
        - name: Photography
          url: photography/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Blog
          url: blog/
          weight: 4


params:
    description: "I am a Masters Student in Computer Science at Stanford University. My goal is to advance the development of intelligent systems that understand the world around them. My interests include Mathematics, Philosophy, Finance, Psychology, and more. In my spare time, I play racket sports, shoot film, and search for new vinyl records. I'm based in SF."
    author: Ali Hindy
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","projects","photography","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ali Hindy
          subtitle: "I am a Masters Student in Computer Science at Stanford University. My goal is to advance the development of intelligent systems that understand the world around them. My interests include Mathematics, Philosophy, Finance, Psychology, and more. In my spare time, I play racket sports, shoot film, and search for new vinyl records. I'm based in SF."
          imageUrl: "profile_pic.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ali Hindy
          buttons:
            - name: Blog
              url: blog/
            - name: Books
              url: books/
            - name: Projects
              url: projects/
            - name: Photography
              url: photography/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ali@hindy.co
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=lVfedjoAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ali-hindy
        - name: Twitter
          url: https://twitter.com/ali-hindy-2

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ali Hindy"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2